version: "3.9"
services:
  postgres:
    container_name: postgres_locale
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
